name: Flask API Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

      - name: Smoke test API
        run: |
          python -m flask --app app run --host=127.0.0.1 --port=5001 & sleep 5
          curl -f http://127.0.0.1:5001/api/v1/health
